### ISSUE TITLE
Porque não usar o projeto de tradução oficial?

### ISSUE THREAD

**Issue by luzfcb** [johnidm/traducao-pt-BR-getting-started-Django#1]
Ola, já há à um bom tempo, o projeto de tradução oficial da documentação do Django para varias línguas, dentre elas, português do brasil, gerenciado pela Django Software Foundation. 

Para mim, seria mais logico traduzir lá, porque via Transifex, assim que a documentação oficial em inglês, for modificada, as novas strings ficam disponíveis para traduzir.

https://www.transifex.com/projects/p/django-docs/translate/#pt_BR

**Comment by johnidm** [comment]
@luzfcb pra falar a verdade não tinha conhecimento da tradução pelo Transifex.

Realmente não faz sentido ter duas traduções simultâneas ainda mais se a do Transifex é oficial.

Vou ver com a galera aqui o que iremos fazer.

Obrigado.
